server:
  port: 8090
management:
  server:
    port: 8190


feature-flags:
  is-bulk-upload-enabled: true
  is-requested-and-calculated-swap-enabled: true
  is-full-claim-details-enabled: true
  is-claim-amendment-enabled: true

maintenance:
  disable-at-time: 2023-12-31T23:59:59Z
  outage-banner-message: Disabled

claims-api:
  # Env var for docker-compose to override to docker host if required
  url: ${CLAIMS_API:http://localhost:8082}
  access-token: f67f968e-b479-4e61-b66e-f57984931e56

logging:
  structured:
    format:
      console: # disables structured logging locally
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr{faint} %clr([%15.15t]){faint} %clr([%X{traceId:-},%X{spanId:-}]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
