services:
  amend-ui:
    container_name: amend-a-claim-app
    profiles:
      - application
    depends_on:
      - amend-redis
    build:
      context: .
      dockerfile: Dockerfile_internal
      args:
        - BUILD_SOURCE=internal
      secrets:
        - github_actor
        - github_token
    # Information on why these ports here: https://github.com/ministryofjustice/laa-data-claims-parent#exposed-ports
    ports:
      - "8090:8090"
      - "8190:8190"
      - "5090:5005"
    environment:
      AZURE_CLIENT_ID: ${AMEND_SILAS_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AMEND_SILAS_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AMEND_SILAS_TENANT_ID}
      BASE_URL_HOMEPAGE: http://localhost:8090
      FEEDBACK_URL: https://www.smartsurvey.co.uk/s/AaBC_Beta_DevTest
      LAA_URL: https://dev.your-legal-aid-services.service.justice.gov.uk
      SENTRY_ENABLED: false # Disabled for docker environment
      REDIS_URL: redis://amend-redis:6379
      CLAIMS_API: http://host.docker.internal:8080
      CLAIMS_TOKEN: f67f968e-b479-4e61-b66e-f57984931e56
      PROVIDER_API: ${PROVIDER_DETAILS_API_HOSTNAME}
      PROVIDER_TOKEN: ${PROVIDER_DETAILS_API_ACCESS_TOKEN}
      SPRING_PROFILES_ACTIVE: docker
      IS_BULK_UPLOAD_ENABLED: true
      IS_STAGE_DISBURSEMENT_ENABLED: true
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  amend-redis:
    image: redis:8-alpine
    container_name: amend-redis
    restart: always
    ports:
      - "6390:6379" #Updated to 6390 to avoid conflict with SaBC Redis instance
    command: redis-server --appendonly yes
    volumes:
      - amend_redis_data:/data
  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - "8081:8080" # Expose WireMock on port 8081
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    command:
      - -local-response-templating

volumes:
  amend_redis_data:
