# Specify java runtime base image
FROM gradle:9.4.1-jdk25 AS spring-builder

# Define a volume to safely store temporary files across restarts
VOLUME /tmp
WORKDIR /app

# Copy the project files into the container for building
COPY . .

# Build the JAR using Gradle, with caching and secret injection for GitHub credentials
RUN --mount=type=cache,target=/root/.gradle \
    --mount=type=secret,id=github_actor \
    --mount=type=secret,id=github_token \
    export GITHUB_ACTOR="$(cat /run/secrets/github_actor)" && \
    export GITHUB_TOKEN="$(cat /run/secrets/github_token)" && \
    gradle assemble

# Use a lightweight runtime image
FROM amazoncorretto:25.0.2-alpine3.23

VOLUME /tmp
WORKDIR /app

# Copy only the built JAR from the builder stage
COPY --from=spring-builder /app/build/libs/laa-amend-a-claim-1.0.0.jar /app/application.jar

# Create a group and non-root user (Alpine syntax)
RUN addgroup -S appgroup && adduser -u 1001 -S appuser -G appgroup

# Set the default user
USER 1001

# Expose the port that the application will run on
EXPOSE 8090

# Run the JAR file
CMD ["java", "-jar", "application.jar"]