apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: https
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
