{{- if .Values.laaAmendAClaim.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-amend-a-claim" .Release.Name }}
  labels:
    app: {{ printf "%s-amend-a-claim" .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ printf "%s-amend-a-claim" .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.laaAmendAClaim.service.port }}
      targetPort: http
{{- end }}
