{{- if .Values.laaAmendAClaim.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "e2e-stack.amendName" . }}
  labels:
    {{- include "e2e-stack.labels" . | nindent 4 }}
    app: {{ include "e2e-stack.amendName" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "e2e-stack.amendName" . }}
  ports:
    - name: http
      port: {{ .Values.laaAmendAClaim.service.port }}
      targetPort: http
{{- end }}
