{{- if .Values.dataClaimsApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-data-claims-api" .Release.Name }}
  labels:
    app: {{ printf "%s-data-claims-api" .Release.Name }}
spec:
  type: {{ .Values.dataClaimsApi.service.type }}
  selector:
    app: {{ printf "%s-data-claims-api" .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.dataClaimsApi.service.port }}
      targetPort: http
    {{- if .Values.dataClaimsApi.service.metricsPort }}
    - name: metrics
      port: {{ .Values.dataClaimsApi.service.metricsPort }}
      targetPort: metrics
    {{- end }}
    {{- if .Values.dataClaimsApi.postgres.enabled }}
    - name: postgres
      port: 5435
      targetPort: postgres
    {{- end }}
{{- end }}
