package uk.gov.justice.laa.amend.claim.viewmodels.viewfield;

public enum MeetingsAttended implements FieldOption {
  NO_MEETINGS_ATTENDED("MTGA01"),
  TRIBUNAL_HEARING_ONLY("MTGA02"),
  HOSPITAL_MANAGERS_REVIEW_ONLY("MTGA03"),
  SECTION_117_MEETING_ONLY("MTGA04"),
  CPA_ONLY("MTGA05"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW("MTGA06"),
  TRIBUNAL_HEARING_SECTION_117_MEETING("MTGA07"),
  TRIBUNAL_HEARING_CPA("MTGA08"),
  HOSPITAL_MANAGERS_REVIEW_SECTION_117_MEETING("MTGA09"),
  HOSPITAL_MANAGERS_REVIEW_CPA("MTGA10"),
  SECTION_117_MEETING_CPA("MTGA11"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW_SECTION_117_MEETING("MTGA12"),
  TRIBUNAL_HEARING_SECTION_117_MEETING_CPA("MTGA13"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW_CPA("MTGA14"),
  HOSPITAL_MANAGERS_REVIEW_SECTION_117_MEETING_CPA("MTGA15"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW_SECTION_117_MEETING_CPA("MTGA16"),
  TRIBUNAL_HEARING_APPLICATION_FOR_REVIEW_APPEAL("MTGA17"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW_APPLICATION_FOR_REVIEW_APPEAL("MTGA18"),
  TRIBUNAL_HEARING_SECTION_117_MEETING_APPLICATION_FOR_REVIEW_APPEAL("MTGA19"),
  TRIBUNAL_HEARING_CPA_APPLICATION_FOR_REVIEW_APPEAL("MTGA20"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW_SECTION_117_MEETING_APPLICATION_FOR_RE("MTGA21"),
  TRIBUNAL_HEARING_SECTION_117_MEETING_CPA_APPLICATION_FOR_REVIEW_APPEAL("MTGA22"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW_CPA_APPLICATION_FOR_REVIEW_APPEAL("MTGA23"),
  TRIBUNAL_HEARING_HOSPITAL_MANAGERS_REVIEW_SECTION_117_MEETING_CPA_APPLICATION_FO("MTGA24");

  private final String value;

  MeetingsAttended(String value) {
    this.value = value;
  }

  @Override
  public String value() {
    return value;
  }
}
