package uk.gov.justice.laa.amend.claim.viewmodels.viewfield;

public enum StageReached implements FieldOption {
  ADVICE_AND_ASSISTANCE_NOT_AT_THE_POLICE_STATION("INVA"),
  POLICE_STATION_TELEPHONE_ADVICE_ONLY("INVB"),
  POLICE_STATION_ATTENDANCE("INVC"),
  INVD("INVD"),
  WARRANT_OF_FURTHER_DETENTION_INCLUDING_ARMED_FORCES_CUSTODY_HEARINGS("INVE"),
  INVF("INVF"),
  INVG("INVG"),
  POLICE_STATION_POST_CHARGE_ATTENDANCE("INVH"),
  INVI("INVI"),
  INVJ("INVJ"),
  ADVOCACY_ASSISTANCE_IN_MAGISTRATES_COURT_ON_APPLICATIONS_TO_EXTEND_PRE_CHARGE_BA("INVK"),
  ADVOCACY_ASSISTANCE_IN_MAGISTRATES_COURT_ON_APPLICATION_TO_VARY_PRE_CHARGE_BAIL("INVL"),
  PRE_CHARGE_ENGAGEMENT_ADVICE_AND_ASSISTANCE("INVM"),
  PRISON_LAW_FREE_STANDING_ADVICE_AND_ASSISTANCE("PRIA"),
  DISCIPLINARY_CASES_ADVOCACY_ASSISTANCE("PRIB"),
  PAROLE_BOARD_CASES_ADVOCACY_ASSISTANCE("PRIC"),
  ADVOCACY_ASSISTANCE_AT_SENTENCE_REVIEWS("PRID"),
  ADVOCACY_ASSISTANCE_AT_PAROLE_BOARD_RECONSIDERATION_SET_ASIDE_HEARINGS("PRIE"),
  PROC("PROC"),
  ADVICE_AND_ASSISTANCE_AND_ADVOCACY_ASSISTANCE_BY_A_COURT_DUTY_SOLICITOR("PROD"),
  MAGISTRATES_COURT_UNDESIGNATED_AREA_LOWER_STANDARD_FEE("PROE"),
  MAGISTRATES_COURT_UNDESIGNATED_AREA_HIGHER_STANDARD_FEE("PROF"),
  PRESCRIBED_PROCEEDINGS_REPRESENTATION_IN_THE_CROWN_COURT("PROH"),
  PROI("PROI"),
  SECOND_CLAIM_FOR_DEFERRED_SENTENCE("PROJ"),
  MAGISTRATES_COURT_DESIGNATED_AREA_LOWER_STANDARD_FEE("PROK"),
  MAGISTRATES_COURT_DESIGNATED_AREA_HIGHER_STANDARD_FEE("PROL"),
  PRE_ORDER_COVER("PROP"),
  EARLY_COVER("PROT"),
  REFUSED_MEANS_TEST_FORM_COMPLETION_FEE("PROU"),
  BREACH_OF_PART_1_INJUNCTIONS_UNDER_ASBCP_ACT("PROV"),
  SENDING_HEARING_FIXED_FEE("PROW"),
  ADVICE_AND_ASSISTANCE_IN_RELATION_TO_AN_APPEAL_EXCEPT_CCRC("APPA"),
  ADVICE_AND_ASSISTANCE_IN_RELATION_TO_A_CCRC_APPLICATION("APPB"),
  APPC("APPC"),
  LEGAL_HELP_AND_ASSOCIATED_CIVIL_WORK_MISCELLANEOUS("ASMS"),
  LEGAL_HELP_AND_ASSOCIATED_CIVIL_WORK_PUBLIC_LAW("ASPL"),
  PART_1_INJUNCTION_ANTI_SOCIAL_BEHAVIOUR_CRIME_AND_POLICING_ACT_2014("ASAS"),
  YOUTH_COURT_UNDESIGNATED_AREA_LOWER_STANDARD_FEE("YOUE"),
  YOUTH_COURT_UNDESIGNATED_AREA_HIGHER_STANDARD_FEE("YOUF"),
  YOUTH_COURT_DESIGNATED_AREA_LOWER_STANDARD_FEE("YOUK"),
  YOUTH_COURT_DESIGNATED_AREA_HIGHER_STANDARD_FEE("YOUL"),
  YOUTH_COURT_UNDESIGNATED_AREA_SECOND_CLAIM_FOR_DEFERRED_SENTENCE("YOUX"),
  YOUTH_COURT_DESIGNATED_AREA_SECOND_CLAIM_FOR_DEFERRED_SENTENCE("YOUY"),
  VOID("VOID");

  private final String value;

  StageReached(String value) {
    this.value = value;
  }

  @Override
  public String value() {
    return value;
  }
}
