apiVersion: v1
kind: ConfigMap
metadata:
  name: amend-a-bulk-claim-maintenance
data:
  enabled: "false"                     # "true" | "false"
  title: "Service maintenance"
  message: "We are performing scheduled maintenance. Expected return: 09:00"
  bypassPassword: "{{ .Values.maintenance.bypassPassword}}" # empty to be set in deployment
