apiVersion: v1
kind: ConfigMap
metadata:
  name: amend-bulk-claim-maintenance
data:
  enabled: "false"                     # "true" | "false"
  title: "Service maintenance"
  message: "We are performing scheduled maintenance. Expected return: 09:00"