apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "laa-amend-a-claim.fullname" . }}-maintenance
data:
  enabled: "false"                     # "true" | "false"
  title: "Service maintenance"
  message: "We are performing scheduled maintenance. Expected return: 09:00"
  bypassPassword: "{{ .Values.maintenance.bypassPassword}}" # empty to be set in deployment
