apiVersion: v1
kind: ConfigMap
metadata:
  name: amend-bulk-claim-maintenance
  labels:
      {{- include "laa-amend-a-claim.labels" . | nindent 4 }}
data:
  enabled: "false"                     # "true" | "false"
  title: "Service maintenance"
  message: "We are performing scheduled maintenance. Expected return: 09:00"