name: laa-amend-a-claim
namespace: dev
replicaCount: 3

ingress:
  className: "modsec-non-prod"
  host: "laa-amend-a-claim-dev.apps.live.cloud-platform.service.justice.gov.uk"
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-amend-a-claim-ingress-dev-green"


secrets:
  azureClientId:
    name: laa-amend-a-claim-azure-client-id
    key: AZURE_CLIENT_ID
  azureClientSecret:
    name: laa-amend-a-claim-azure-client-secret
    key: AZURE_CLIENT_SECRET
  azureTenant:
    name: laa-amend-a-claim-azure-tenant
    key: AZURE_TENANT_ID
  baseUrl:
    name: laa-amend-a-claim-base-url
    key: BASE_URL_HOMEPAGE

sentry:
  dsn: https://07a4e036e1305d8dd00a9fede404c9e4@o345774.ingest.us.sentry.io/4510119326908416
  environment: development