name: Branch Naming Convention Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Checking branch name: $BRANCH_NAME"
          
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|spike)\/[a-z]+-[0-9]{2,}-[a-z0-9-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the required pattern."
            echo "Expected format: feature|bugfix|hotfix/abc-123-description"
            exit 1
          fi
