name: Deploy Development

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on (default: main)'
        required: false
        default: 'main'

  push:
    branches: [main]

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.inputs.branch || github.ref_name }}
      environment: dev
      SENTRY_ENV: development
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}

