name: Security Scan

on:
  push:

permissions:
  contents: read
  security-events: write

jobs:
  vulnerability-scan-app:
    name: Vulnerability Scan - Application
    runs-on: ubuntu-latest
    env:
      SNYK_TEST_EXCLUDE: build,generated
      SNYK_TARGET_REFERENCE: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Obtain Short-lived Snyk token
        id: auth
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/snyk-auth@6db001458db30ae747d9eb8eb25707ce52b359bc
        with:
          client_id: ${{ secrets.SNYK_CLIENT_ID }}
          client_secret: ${{ secrets.SNYK_CLIENT_SECRET }}

      - name: Run Snyk app vulnerability scan
        run: snyk test --severity-threshold=low --sarif-file-output=snyk-app.sarif
        env:
          SNYK_OAUTH_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Upload result to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@2f90a82ab7eece7aa899ce5d384db49efd7337ea
        with:
          sarif_file: snyk-app.sarif
          category: snyk-app
